//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoryTeller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Theme
    {
        public int ThemeID { get; set; }
        public Nullable<int> PirateID { get; set; }
        public Nullable<int> PrincessID { get; set; }
        public Nullable<int> AnimalID { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Pirate Pirate { get; set; }
        public virtual Princesse Princesse { get; set; }
    }
}
